package com.f1db.plugin.schema

/**
 * The race data types.
 *
 * @author Marcel Overdijk
 */
enum class RaceDataType {

    PRE_QUALIFYING_RESULT,
    FREE_PRACTICE_1_RESULT,
    FREE_PRACTICE_2_RESULT,
    FREE_PRACTICE_3_RESULT,
    FREE_PRACTICE_4_RESULT,
    QUALIFYING_1_RESULT,
    QUALIFYING_2_RESULT,
    QUALIFYING_RESULT,
    SPRINT_QUALIFYING_RESULT,
    SPRINT_STARTING_GRID_POSITION,
    SPRINT_RACE_RESULT,
    WARMING_UP_RESULT,
    STARTING_GRID_POSITION,
    RACE_RESULT,
    FASTEST_LAP,
    PIT_STOP,
    DRIVER_OF_THE_DAY_RESULT
}