INSERT INTO race
( id
, year
, round
, date
, time
, grand_prix_id
, official_name
, qualifying_format
, sprint_qualifying_format
, circuit_id
, circuit_type
, course_length
, laps
, distance
, scheduled_laps
, scheduled_distance
, pre_qualifying_date
, pre_qualifying_time
, free_practice_1_date
, free_practice_1_time
, free_practice_2_date
, free_practice_2_time
, free_practice_3_date
, free_practice_3_time
, free_practice_4_date
, free_practice_4_time
, qualifying_1_date
, qualifying_1_time
, qualifying_2_date
, qualifying_2_time
, qualifying_date
, qualifying_time
, sprint_qualifying_date
, sprint_qualifying_time
, sprint_race_date
, sprint_race_time
, warming_up_date
, warming_up_time
)
VALUES
( :id
, :year
, :round
, :date
, :time
, :grandPrixId
, :officialName
, :qualifyingFormat
, :sprintQualifyingFormat
, :circuitId
, :circuitType
, :courseLength
, :laps
, :distance
, :scheduledLaps
, :scheduledDistance
, :preQualifyingDate
, :preQualifyingTime
, :freePractice1Date
, :freePractice1Time
, :freePractice2Date
, :freePractice2Time
, :freePractice3Date
, :freePractice3Time
, :freePractice4Date
, :freePractice4Time
, :qualifying1Date
, :qualifying1Time
, :qualifying2Date
, :qualifying2Time
, :qualifyingDate
, :qualifyingTime
, :sprintQualifyingDate
, :sprintQualifyingTime
, :sprintRaceDate
, :sprintRaceTime
, :warmingUpDate
, :warmingUpTime
);
