package com.f1db.plugin.writer.sql.mapper

import org.mapstruct.factory.Mappers

val continentMapper = Mappers.getMapper(ContinentMapper::class.java)
val countryMapper = Mappers.getMapper(CountryMapper::class.java)
val driverMapper = Mappers.getMapper(DriverMapper::class.java)
val driverFamilyRelationshipMapper = Mappers.getMapper(DriverFamilyRelationshipMapper::class.java)
val constructorMapper = Mappers.getMapper(ConstructorMapper::class.java)
val constructorPreviousNextConstructorMapper = Mappers.getMapper(ConstructorPreviousNextConstructorMapper::class.java)
val engineManufacturerMapper = Mappers.getMapper(EngineManufacturerMapper::class.java)
val tyreManufacturerMapper = Mappers.getMapper(TyreManufacturerMapper::class.java)
val entrantMapper = Mappers.getMapper(EntrantMapper::class.java)
val circuitMapper = Mappers.getMapper(CircuitMapper::class.java)
val grandPrixMapper = Mappers.getMapper(GrandPrixMapper::class.java)
val seasonMapper = Mappers.getMapper(SeasonMapper::class.java)
val seasonEntrantMapper = Mappers.getMapper(SeasonEntrantMapper::class.java)
val seasonEntrantConstructorMapper = Mappers.getMapper(SeasonEntrantConstructorMapper::class.java)
val seasonEntrantTyreManufacturerMapper = Mappers.getMapper(SeasonEntrantTyreManufacturerMapper::class.java)
val seasonEntrantDriverMapper = Mappers.getMapper(SeasonEntrantDriverMapper::class.java)
val seasonDriverStandingMapper = Mappers.getMapper(SeasonDriverStandingMapper::class.java)
val seasonConstructorStandingMapper = Mappers.getMapper(SeasonConstructorStandingMapper::class.java)
val raceMapper = Mappers.getMapper(RaceMapper::class.java)
val racePracticeResultMapper = Mappers.getMapper(RacePracticeResultMapper::class.java)
val raceQualifyingResultMapper = Mappers.getMapper(RaceQualifyingResultMapper::class.java)
val raceRaceResultMapper = Mappers.getMapper(RaceRaceResultMapper::class.java)
val raceStartingGridPositionMapper = Mappers.getMapper(RaceStartingGridPositionMapper::class.java)
val raceFastestLapMapper = Mappers.getMapper(RaceFastestLapMapper::class.java)
val racePitStopMapper = Mappers.getMapper(RacePitStopMapper::class.java)
val raceDriverOfTheDayResultMapper = Mappers.getMapper(RaceDriverOfTheDayResultMapper::class.java)
val raceDriverStandingMapper = Mappers.getMapper(RaceDriverStandingMapper::class.java)
val raceConstructorStandingMapper = Mappers.getMapper(RaceConstructorStandingMapper::class.java)
